import chicken from './components/images/chicken.jpeg'
import biryani from './components/images/Biryani.jpeg'
import dahl from './components/images/dahl.webp'

export interface Recipe {
    name: string;
    description: string;
    image: string;
    ingredients: string[];
    instructions: string[];
  }

  const recipes: Recipe[] = [
	{ 
     name: "Chicken Tikka Masala",
     description: "Welcome to the most creamy, luscious, medium-spicy, must-have-it-NOW chicken tikka masala.",
     image: chicken,
     ingredients: ["28 oz (800g) boneless and skinless chicken thighs cut into bite-sized pieces", 
     "1 cup plain yogurt", "1 1/2 tablespoons minced garlic", "1 tablespoon ginger", "2 teaspoons garam masala", "1 teaspoon turmeric", "1 teaspoon ground cumin", "1 teaspoon Kashmiri chili (or 1/2 teaspoon ground red chili powder", "1 teaspoon of salt", "2 tablespoons of vegetable/canola oil", "2 tablespoons butter", 
    "2 small onions (or 1 large onion) finely diced", "1 1/2 tablespoons garlic finely grated ", "1 tablespoon ginger finely grated", 
    "1 1/2 teaspoons garam masala", " 1 1/2 teaspoons ground cumin",
    "1 teaspoon turmeric powder", "1 teaspoon ground coriander", 
    "14 oz (400g) tomato puree (tomato sauce/Passata)", "1 teaspoon Kashmiri chili (optional for colour and flavour)", 
    "1 teaspoon ground red chili powder (adjust to your taste preference)",
    "1 teaspoon salt",
    "1 1/4 cups of heavy or thickened cream (use evaporated milk for lower calories)",
    "1 teaspoon brown sugar","1/4 cup water if needed",
    "4 tablespoons Fresh cilantro or coriander to garnish"],
     instructions: ["In a bowl, combine chicken with all of the ingredients for the chicken marinade; let marinate for 10 minutes to an hour (or overnight if time allows).",
     "Heat oil in a large skillet or pot over medium high heat.",
    "When sizzling, add chicken pieces in batches of two or three, making sure not to crowd the pan.",
    "Fry until browned for only 3 minutes on each side. Set aside and keep warm. (You will finish cooking the chicken in the sauce.)",
    "Melt the butter in the same pan. Fry the onions until soft (about 3 minutes) while scraping up any browned bits stuck on the bottom of the pan.",
    "Add garlic and ginger and sauté for 1 minute until fragrant, then add garam masala, cumin, turmeric and coriander. Fry for about 20 seconds until fragrant, while stirring occasionally.",
    "Pour in the tomato puree, chili powders and salt. Let simmer for about 10-15 minutes, stirring occasionally until sauce thickens and becomes a deep brown red colour.",
    "Stir the cream and sugar through the sauce.",
    "Add the chicken and its juices back into the pan and cook for an additional 8-10 minutes until chicken is cooked through and the sauce is thick and bubbling. Pour in the water to thin out the sauce, if needed.",
    "Garnish with cilantro (coriander) and serve with rice or naan bread!"]
    },

	{
     name: "Mutton Biryani",
     description: "A hearty mutton biryani that will impress your guests instantly. Mutton Biryani is a dish that nobody can ever resist!!",
     image: biryani,
     ingredients: ["1 Star anise",
    "500 gms basmati rice, blanched",
    "2 Bay leaves ",
    "2 Black cardamom",
    " 2 tsp black cumin seeds",
    " Black peppercorn",
    "6 Green cardamom",
    "2 Cinnamon sticks",
    "6 Cloves",
    "1 tsp fennel",
    "1/4 Jaiphal",
    "1 Javitri",
    "3 tsp Salt",
    "1 kg mutton (cut in 2 inches pieces, preferably front leg part and avoid shoulder cut)",
    "1 tbsp garam masala",
    "1 tbsp garlic paste",
    "1 tbsp ginger paste",
    "3 tbsp raw papaya paste",
    "4 tbsp hung curd",
    "1 Lemon (juiced)",
    "Coriander powder",
    "Cumin powder",
    "1 tbsp red chilli powder",
    "1 tsp salt",
    "1 teaspoon ground red chili powder (adjust to your taste preference)",
    "1 teaspoon salt",
    "1 1/4 cups of heavy or thickened cream (use evaporated milk for lower calories)",
    "1 teaspoon brown sugar",
    "1/4 cup water if needed",
    "4 tablespoons Fresh cilantro or coriander to garnish",
    "4 onions, sliced ",
    " 2 tomatoes, chopped ",
    " 1/4 cup milk (warm)",
    "Ghee",
    "Saffron strands",
    "Oil",
    "Rose water ",
    " Kewra essence",
    "4 green chillies",],
     instructions: ["To the mutton add the beaten curd, ginger-garlic paste, raw papaya paste, chilli powder, salt, lemon juice, garam masala.",
    "Allow the mutton to marinate for 3 hours.",
    "Slice 2 onions very thinly. Separate the slices.",
    "In a pan or kadai add oil and fry the onion slices till nicely brown.",
    "Take care not to burn them. Fry in small batches. Do not put all the slices at a time, that will lead to lumpy messy onions.",
    "Make sure all the onion slices frying are dipped in oil, if needed add more oil. Keep stirring continuously but gently for an even brown color.",
    "Take the fried onions out with a slotted spoon or ladle.",
    "Keep them on a paper-towel lined plate. This crispy brown fried onion slices are called Barista. ",
    " Heat ghee in a thick-bottomed pan.",
    " Add remaining sliced onions and green chillies. Cook, stirring continuously, till onions are light golden brown.",
    "Add ginger paste and garlic paste and mix well.",
    "Add marinated mutton and cook on high heat for seven to eight minutes. ",
    "Add coriander powder, cumin powder and red chilli powder. Mix thoroughly.",
    "Stir in three cups of water, bring it to a boil, reduce heat and cook covered till mutton is almost cooked.",
    "Add tomatoes, salt, garam masala powder and fresh coriander leaves.",
    "Cook for 15 minutes on medium heat, stirring occasionally. The ghee would be separated from the spices and there should not be any watery gravy to the meat. ",
    "Use only good quality long grain Basmati rice. Soak the rice for 20 minutes in water. Wash well till the water runs clear. Drain all the water.",
    "In a small piece of cloth take cardamom, cinnamon, cloves, javitri, jaiphal, black peppercorn, shahi jeera, star anise and tie a knot to make a bag (potli).",
    "Bring 750 ml water to boil, add rice, bay leaf, salt and potli, cover and cook till rice is done 1/3rd. ",
    "Drain the water & remove the whole masala potli.",
    "Take 1/4th cup warm milk in a cup and dissolve saffron strands in the milk.",
    "Cover and wait for 20 minutes. Add rose water and kewra essence in the milk. Mix well and cover. Keep aside.",
    "Take a large heavy bottom pan with tight fitting lid.",
    "Add 2tbsp ghee to the pan. Melt the ghee on low heat. Turn and rotate the pan carefully so the ghee can coat the bottom and sides of the pan. Switch off the heat.",
    "Add a layer of cooked rice, then cooked meat pieces, sprinkle saffron water, add fried onion slices and ghee.",
    "Again add a layer of rice, then meat...go on like this till you are done. Top and bottom layer will be of rice.",
    "Cover with chopped pudina and coriander, fried onion and slit green chillies and juice of half a lemon.",
    "Put the lid on. Seal the pan with flour dough or aluminium foil, then put the lid. Keep the heat to lowest. And cook the Biryani in this 'Dum' process for 40 minutes. ",
    "Make sure your pan is heavy-bottomed or the rice will burn. Or you can place a flat tawa then keep the pan on that tawa.",
    "After 40 minutes switch off the heat and let the biryani stand for another 10 minutes. Transfer to a serving bowl.",
    "Serve with raita and salad."] 
    },

	{
     name: "Red Lentil Dahl",
     description: "You can't go wrong with this Red Lenti Dahl - it's creamy, spicy, filling, and delicious!",
     image: dahl,
     ingredients: ["1 tablespoon olive oil",
     "1 large yellow onion, chopped small",
    "5 cloves garlic, minced",
    "1 tablespoon fresh ginger, peeled and grated",
    "1 tablespoon garam masala",
    "1/2 teaspoon red pepper chili flakes",
    "1 1/2 cups dried red lentils",
    "14 ounce can diced tomatoes",
    "13.5 ounce can full fat coconut milk",
    "3 cups vegetable broth",
    "1 teaspoon salt, or to taste",
    "half a lemon, juiced",
    "3-4 cups baby spinach",
    "4 cups cooked brown or white rice",
    "Vegan Naan"],
     instructions: ["In a large pot or pan over medium heat, sauté the chopped onion in the olive oil for 5 minutes, stirring frequently.", "Then add the garlic and ginger and cook 1 more minute, until fragrant.",
    "Add the garam masala, turmeric and red pepper flakes to the pan and stir into the onion mixture.",
    "Add a few tablespoons of water if the mixture is too dry.",
    "Now add the dried lentils, canned tomatoes and their juices, coconut milk and vegetable broth to the pan. Stir well and turn the heat to high.",
    "Bring to a boil, then lower heat and simmer for about 15 minutes, until the lentils are cooked and soft. Stir occasionally.",
    "Squeeze the lemon juice into the pan, and stir in the spinach as well until wilted. Add salt to taste. I used 1 teaspoon.",
    "Serve with brown or white rice and Vegan Naan. Enjoy!",]} 
    ];

export default recipes;